<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>json</string>
	</array>
	<key>name</key>
	<string>JSON Key-Value</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Single-line comment</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.single.line.jsonkv</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>Multi-line comment</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.jsonkv</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.name.jsonkv</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Key names</string>
			<key>match</key>
			<string>"(?i)([^\"]+)"\s*?:</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>String values</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.jsonkv</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Escape characters</string>
					<key>match</key>
					<string>\\[tnr"]</string>
					<key>name</key>
					<string>constant.character.escape.jsonkv</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric values</string>
			<key>match</key>
			<string>\d+(?:.\d+)?</string>
			<key>name</key>
			<string>constant.numeric.jsonkv</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean values</string>
			<key>match</key>
			<string>true|false</string>
			<key>name</key>
			<string>constant.language.boolean.jsonkv</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Null value</string>
			<key>match</key>
			<string>null</string>
			<key>name</key>
			<string>constant.language.null.jsonkv</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.json</string>
	<key>uuid</key>
	<string>4e5a820c-0650-4de9-b793-201999eeeb4f</string>
</dict>
</plist>
